### ISSUE TITLE
NullReferenceException on Diadem Fishing

### ISSUE THREAD

**Issue by doe-el** [kalilistic/ACT.Kapture#49]
Hi there,
The following exception is being thrown while fishing in the diadem.
Best Wishes,
Doe

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ACT_FFXIV_Kapture.Plugin.LogLineParserBase.IsObtainFish()
   at ACT_FFXIV_Kapture.Plugin.LogLineParserBase.ParseLootEvent()
   at ACT_FFXIV_Kapture.Plugin.LogLineParserBase.Parse(ACTLogLineEvent actLogLineEvent)
   at ACT_FFXIV_Kapture.Plugin.ENLogLineParser.Parse(ACTLogLineEvent actLogLineEvent)
   at ACT_FFXIV_Kapture.Plugin.KaptureData.ACTLogLineCaptured(Object sender, ACTLogLineEvent actLogLineEvent)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.ReadLog()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by kalilistic** [comment]
Hey, sorry for the slow response. I've just released an update with the latest game data - please let me know if it still happens. If you see it again, can you share the line you see in chat when catching the fish.

**Comment by kalilistic** [comment]
Going to close this but feel free to reopen or create a new issue if it's still happening.
