### ISSUE TITLE
ACT Catching Exception

### ISSUE THREAD

**Issue by Blazewardog** [kalilistic/ACT.Kapture#51]
Getting the following exception sometimes during Zadnor when getting loot. Not doing anything in particular, has fired for items that have existed for a while. Might be outside the zone also but I've only done my weekly Savage clear besides Zadnor this week.

System.NullReferenceException: Object reference not set to an instance of an object.
   at ACT_FFXIV_Kapture.Plugin.LogLineParserBase.IsExcludedLootEvent()
   at ACT_FFXIV_Kapture.Plugin.LogLineParserBase.Parse(ACTLogLineEvent actLogLineEvent)
   at ACT_FFXIV_Kapture.Plugin.ENLogLineParser.Parse(ACTLogLineEvent actLogLineEvent)
   at ACT_FFXIV_Kapture.Plugin.KaptureData.ACTLogLineCaptured(Object sender, ACTLogLineEvent actLogLineEvent)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.ReadLog()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
*****
***** 2021-06-04T20:10:51 - Notification
Event Handler Unhandled Exceptions
In the last minute, these plugins caused exceptions in event handlers:

Aetherbridge, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null [1 time(s)]

Upon looking at that function, this line looks the most suspicious to me, guessing GetCurrentLocation is returning null
var territoryTypeId = Context.KaptureData.LocationService.GetCurrentLocation().TerritoryTypeId;

**Comment by kalilistic** [comment]
I was a few months out of date so could be the issue. Just updated the data and pushed a new release.

**Comment by Blazewardog** [comment]
Haven't had a popup from ACT in about half an hour with drops happening there. Seems fixed.
